# -*- coding: utf-8 -*-
"""AI4021 - HW1 - 2 - Python Tutorial 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19PbjHbQCReCSxNh5OoIxrWw5_H1BcYX4

**Problem 1:** Create a NumPy array of 20 random integers between 1 and 100. Calculate the mean, median, and standard deviation of the array.
"""

import numpy as np

random_array = np.random.randint(1, 101, 20)

mean_value = np.mean(random_array)
median_value = np.median(random_array)
std_deviation = np.std(random_array)

print("Random Array:", random_array)
print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_deviation)

"""**Problem 2:** Create a Pandas DataFrame with three columns - 'Name', 'Age', and 'City' - and at least five rows of data. Perform a basic data exploration by displaying the first 3 rows, the last 2 rows, and a summary of statistics for the 'Age' column."""

import pandas as pd

data = {'Name': ['Ali', 'Babak', 'Changiz', 'Davood', 'Effat'],
        'Age': [25, 30, 22, 28, 26],
        'City': ['Nahavand', 'Semnan', 'Lahijan', 'shiraz', 'Mashhad']}

df = pd.DataFrame(data)

print("First 3 rows:")
print(df.head(3))

print("\nLast 2 rows:")
print(df.tail(2))

print("\nSummary statistics for the 'Age' column:")
print(df['Age'].describe())

"""**Problem 3:** Create a bar chart using Matplotlib to visualize the following data: Monthly sales for a store (January to May). Use appropriate labels and titles for the chart."""

import matplotlib.pyplot as plt

months = ['فروردین', 'اردیبهشت', 'خرداد', 'تیر', 'مرداد']
sales = [45000, 52000, 60000, 48000, 55000]

plt.bar(months, sales, color='skyblue')

plt.xlabel('ماه')
plt.ylabel('فروش (ريال)')
plt.title('فروش ماهانه (فروردین تا مرداد)')

plt.show()

"""**Problem 4:** Create two NumPy arrays, 'arr1' and 'arr2', both of size 5x5 with random integer values. Perform element-wise addition, subtraction, multiplication, and division between the two arrays."""

import numpy as np

arr1 = np.random.randint(1, 11, size=(5, 5))
arr2 = np.random.randint(1, 11, size=(5, 5))

addition_result = arr1 + arr2

subtraction_result = arr1 - arr2

multiplication_result = arr1 * arr2

division_result = np.divide(arr1, arr2, out=np.zeros_like(arr1, dtype=np.float64), where=arr2 != 0)

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nElement-wise Addition:")
print(addition_result)
print("\nElement-wise Subtraction:")
print(subtraction_result)
print("\nElement-wise Multiplication:")
print(multiplication_result)
print("\nElement-wise Division:")
print(division_result)

"""**Problem 5:** Given a Pandas DataFrame with information about employees, filter and display only the employees who are older than 30 years."""

import pandas as pd

data = {'Name': ['Ali', 'Babak', 'Changiz', 'Davood', 'Effat'],
        'Age': [32, 28, 35, 26, 42]}

employee_data = pd.DataFrame(data)

older_than_30 = employee_data[employee_data['Age'] > 30]

print(older_than_30)

"""**Problem 6:** Create a scatter plot using Matplotlib to visualize a dataset of 100 random (x, y) coordinates. Label the axes appropriately and give the plot a title."""

import matplotlib.pyplot as plt
import numpy as np

np.random.seed(0)
x = np.random.rand(100)
y = np.random.rand(100)

plt.scatter(x, y, marker='o', color='red', s=25)

plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Scatter Plot of Random (x, y) Coordinates')

plt.show()

"""**Problem 7:** Create two NumPy matrices, 'matrix1' (2x3) and 'matrix2' (3x4), with random values. Perform matrix multiplication between the two matrices."""

import numpy as np

matrix1 = np.random.rand(2, 3)
matrix2 = np.random.rand(3, 4)

result_matrix = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult of Matrix Multiplication:")
print(result_matrix)

"""**Problem 8:** Given a Pandas DataFrame containing sales data, calculate and display the total sales for each product category."""

import pandas as pd

data = {'Product': ['A', 'B', 'C', 'A', 'B', 'C'],
        'Category': ['X', 'Y', 'Y', 'Y', 'X', 'X'],
        'Sales': [100, 150, 120, 90, 130, 110]}

sales_data = pd.DataFrame(data)

category_sales = sales_data.groupby('Category')['Sales'].sum().reset_index()

print(category_sales)

"""**Problem 9:** Create a line chart using Matplotlib to visualize the population growth of a city over 10 years. Label the axes and provide a title."""

import matplotlib.pyplot as plt

years = [2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
population = [50000, 52000, 54000, 56000, 59000, 61000, 63000, 65000, 67000, 69000]

plt.plot(years, population, marker='o', linestyle='-', color='b')

plt.xlabel('Year')
plt.ylabel('Population')
plt.title('City Population Growth Over 10 Years')

plt.grid(True)
plt.show()

"""**Problem 10:** Given a Pandas DataFrame containing information about students, add a new column 'Grade' based on the following criteria:
* If 'Score' >= 90, Grade is 'A'
* If 'Score' >= 80, Grade is 'B'
* If 'Score' >= 70, Grade is 'C'
* If 'Score' < 70, Grade is 'D'
"""

import pandas as pd

data = {'StudentName': ['Ali', 'Babak', 'Changiz', 'Davood', 'Effat'],
        'Score': [95, 82, 68, 75, 60]}

student_data = pd.DataFrame(data)

def calculate_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    else:
        return 'D'

student_data['Grade'] = student_data['Score'].apply(calculate_grade)

print(student_data)

"""**Problem 11:** You are given a dataset containing monthly sales data for three products (A, B, and C) over a two-year period. Your task is to perform various data analysis tasks using NumPy, Pandas, and Matplotlib.


*   Dataset:

```
import pandas as pd

data = {
    'Month': pd.date_range(start='2021-01-01', periods=24, freq='M'),
    'Product A Sales': [500, 480, 600, 750, 900, 850, 920, 1100, 1300, 1350, 1500, 1450, 1550, 1600, 1650, 1600, 1500, 1400, 1600, 1700, 1800, 1750, 1850, 1900],
    'Product B Sales': [300, 320, 400, 450, 500, 580, 700, 750, 820, 900, 950, 980, 1050, 1100, 1150, 1200, 1250, 1300, 1350, 1400, 1500, 1600, 1550, 1700],
    'Product C Sales': [200, 210, 250, 280, 320, 350, 380, 400, 420, 440, 460, 480, 500, 520, 540, 560, 580, 600, 620, 640, 660, 680, 700, 720]
}

sales_df = pd.DataFrame(data)
```
*  Tasks:
1. Calculate and display the total sales for each product over the two-year period.

2. Calculate and display the average monthly sales for each product.

3. Find the month with the highest sales for each product, and display the product and the sales value for that month.

4. Calculate and display the percentage change in sales for each product from January to December in the second year (2022).

5. Create a line chart using Matplotlib to visualize the monthly sales data for each product over the two-year period. Label the axes and provide a title for the chart.

6. Calculate the correlation between Product A and Product B sales. Is there a strong correlation between these two products? Display the correlation coefficient.

"""

import pandas as pd
import matplotlib.pyplot as plt

data = {
    'Month': pd.date_range(start='2021-01-01', periods=24, freq='M'),
    'Product A Sales': [500, 480, 600, 750, 900, 850, 920, 1100, 1300, 1350, 1500, 1450, 1550, 1600, 1650, 1600, 1500, 1400, 1600, 1700, 1800, 1750, 1850, 1900],
    'Product B Sales': [300, 320, 400, 450, 500, 580, 700, 750, 820, 900, 950, 980, 1050, 1100, 1150, 1200, 1250, 1300, 1350, 1400, 1500, 1600, 1550, 1700],
    'Product C Sales': [200, 210, 250, 280, 320, 350, 380, 400, 420, 440, 460, 480, 500, 520, 540, 560, 580, 600, 620, 640, 660, 680, 700, 720]
}

sales_df = pd.DataFrame(data)

total_sales = sales_df.sum()
print("Total Sales for Each Product:\n",total_sales)

average_monthly_sales = sales_df.mean()
print("\nAverage Monthly Sales for Each Product:\n",average_monthly_sales)

max_sales_month_A = sales_df['Month'][sales_df['Product A Sales'].idxmax()]
max_sales_A = sales_df['Product A Sales'].max()
max_sales_month_B = sales_df['Month'][sales_df['Product B Sales'].idxmax()]
max_sales_B = sales_df['Product B Sales'].max()
max_sales_month_C = sales_df['Month'][sales_df['Product C Sales'].idxmax()]
max_sales_C = sales_df['Product C Sales'].max()
print(f"\nMonth with Highest Sales for Product A: {max_sales_month_A} (Sales: {max_sales_A})")
print(f"Month with Highest Sales for Product B: {max_sales_month_B} (Sales: {max_sales_B})")
print(f"Month with Highest Sales for Product C: {max_sales_month_C} (Sales: {max_sales_C})")

sales_jan_2022 = sales_df.loc[12:23].sum()
sales_dec_2022 = sales_df.loc[0:11].sum()
percentage_change = ((sales_jan_2022 - sales_dec_2022) / sales_dec_2022) * 100
print(f"\nPercentage Change in Sales from January to December 2022:")
print(percentage_change)

plt.figure(figsize=(10, 6))
plt.plot(sales_df['Month'], sales_df['Product A Sales'], label='Product A')
plt.plot(sales_df['Month'], sales_df['Product B Sales'], label='Product B')
plt.plot(sales_df['Month'], sales_df['Product C Sales'], label='Product C')
plt.xlabel('Month')
plt.ylabel('Sales')
plt.title('Monthly Sales Data Over Two Years')
plt.legend()
plt.grid(True)
plt.show()

correlation = sales_df['Product A Sales'].corr(sales_df['Product B Sales'])
print(f"\nCorrelation between Product A and Product B Sales: {correlation}")